language: php

php:
    - 5.5
    - 5.6

before_script:
    - curl -s http://getcomposer.org/installer | php
    - COMPOSER_ROOT_VERSION=dev-master php composer.phar install --dev

script:
    - bin/atoum

notifications:
    email:
        - geek@atipik.fr
